"""Contract billing ledger and standard ERPNext document event integration."""

from __future__ import annotations

import frappe
from frappe.utils import flt, getdate, nowdate


def _invoice_status(invoice):
    if invoice.docstatus == 2:
        return "Cancelled"
    if invoice.docstatus == 0:
        return "Draft"
    if flt(invoice.outstanding_amount) <= 0:
        return "Paid"
    if flt(invoice.outstanding_amount) < flt(invoice.grand_total):
        return "Partly Paid"
    if invoice.due_date and getdate(invoice.due_date) < getdate(nowdate()):
        return "Overdue"
    return "Unpaid"


def _reference(invoice):
    candidates = (
        ("Occupancy Agreement", invoice.get("estateflow_agreement")),
        ("Property Sale Contract", invoice.get("estateflow_sale_contract")),
        ("Property Reservation", invoice.get("estateflow_reservation")),
    )
    for doctype, name in candidates:
        if name:
            return doctype, name
    return "Sales Invoice", invoice.name


def sync_invoice_billing_event(invoice, method=None):
    """Create or refresh the auditable EstateFlow billing ledger row.

    This handles invoices generated by EstateFlow and invoices entered manually
    whenever an EstateFlow agreement, reservation, sale or property is linked.
    """
    if isinstance(invoice, str):
        invoice = frappe.get_doc("Sales Invoice", invoice)
    has_reference = any(
        invoice.get(fieldname)
        for fieldname in (
            "estateflow_property", "estateflow_agreement", "estateflow_reservation", "estateflow_sale_contract"
        )
    )
    if not has_reference:
        return

    reference_doctype, reference_name = _reference(invoice)
    source = invoice.get("estateflow_billing_source") or "Manual Invoice"
    values = {
        "billing_source": source,
        "status": _invoice_status(invoice),
        "reference_doctype": reference_doctype,
        "reference_name": reference_name,
        "milestone_row": invoice.get("estateflow_milestone_row"),
        "sales_invoice": invoice.name,
        "customer": invoice.customer,
        "company": invoice.company,
        "property": invoice.get("estateflow_property"),
        "space": invoice.get("estateflow_space"),
        "currency": invoice.currency,
        "posting_date": invoice.posting_date,
        "due_date": invoice.due_date,
        "period_start": invoice.get("estateflow_billing_period_start"),
        "period_end": invoice.get("estateflow_billing_period_end"),
        "billed_amount": invoice.grand_total,
        "paid_amount": flt(invoice.grand_total) - flt(invoice.outstanding_amount),
        "outstanding_amount": invoice.outstanding_amount,
    }
    existing = frappe.db.get_value("Contract Billing Event", {"sales_invoice": invoice.name}, "name")
    if existing:
        frappe.db.set_value("Contract Billing Event", existing, values, update_modified=True)
    else:
        try:
            frappe.get_doc({"doctype": "Contract Billing Event", **values}).insert(ignore_permissions=True)
        except frappe.DuplicateEntryError:
            existing = frappe.db.get_value("Contract Billing Event", {"sales_invoice": invoice.name}, "name")
            if existing:
                frappe.db.set_value("Contract Billing Event", existing, values, update_modified=True)
    _sync_milestone(invoice)


def _sync_milestone(invoice):
    row_name = invoice.get("estateflow_milestone_row")
    if not row_name:
        return
    paid = flt(invoice.grand_total) - flt(invoice.outstanding_amount)
    status = _invoice_status(invoice)
    milestone_status = {
        "Draft": "Pending", "Unpaid": "Invoiced", "Overdue": "Invoiced",
        "Partly Paid": "Partly Paid", "Paid": "Paid", "Cancelled": "Pending",
    }[status]
    for child_doctype in ("Agreement Milestone", "Sale Installment"):
        if frappe.db.exists(child_doctype, row_name):
            values = {"status": milestone_status, "sales_invoice": None if status == "Cancelled" else invoice.name}
            meta = frappe.get_meta(child_doctype)
            if meta.has_field("paid_amount"):
                values.update({"paid_amount": paid, "outstanding_amount": invoice.outstanding_amount})
            frappe.db.set_value(child_doctype, row_name, values)
            break


def on_sales_invoice_submit(invoice, method=None):
    sync_invoice_billing_event(invoice, method)
    from estateflow.api.notifications import send_invoice_issued
    send_invoice_issued(invoice)


def on_sales_invoice_update(invoice, method=None):
    sync_invoice_billing_event(invoice, method)


def on_sales_invoice_cancel(invoice, method=None):
    sync_invoice_billing_event(invoice, method)


def on_payment_entry_submit(payment, method=None):
    invoices = {
        row.reference_name for row in payment.references
        if row.reference_doctype == "Sales Invoice" and row.reference_name
    }
    first_invoice = None
    for name in invoices:
        invoice = frappe.get_doc("Sales Invoice", name)
        first_invoice = first_invoice or invoice
        sync_invoice_billing_event(invoice, method)
    if first_invoice:
        values = {}
        for payment_field, invoice_field in (
            ("estateflow_property", "estateflow_property"),
            ("estateflow_space", "estateflow_space"),
            ("estateflow_agreement", "estateflow_agreement"),
            ("estateflow_reservation", "estateflow_reservation"),
        ):
            if payment.meta.has_field(payment_field) and not payment.get(payment_field) and first_invoice.get(invoice_field):
                values[payment_field] = first_invoice.get(invoice_field)
        if values:
            payment.db_set(values)
    from estateflow.api.notifications import send_payment_receipt
    send_payment_receipt(payment)


def on_payment_entry_cancel(payment, method=None):
    invoices = {
        row.reference_name for row in payment.references
        if row.reference_doctype == "Sales Invoice" and row.reference_name
    }
    for name in invoices:
        sync_invoice_billing_event(frappe.get_doc("Sales Invoice", name), method)


@frappe.whitelist()
def rebuild_billing_ledger(company=None):
    frappe.only_for(("System Manager", "EstateFlow Administrator", "Accounts Manager", "Property Manager"))
    filters = {"docstatus": ["<", 2], "estateflow_property": ["is", "set"]}
    if company:
        filters["company"] = company
    names = frappe.get_all("Sales Invoice", filters=filters, pluck="name", limit_page_length=5000)
    for name in names:
        sync_invoice_billing_event(frappe.get_doc("Sales Invoice", name))
    return {"processed": len(names)}
